services:
  ui:
    build:
      args:
        VITE_PAGEWRIGHT_API_URL: http://pagewright.io:8085
        VITE_PAGEWRIGHT_WS_URL: ws://pagewright.io:8085/ws
        VITE_PAGEWRIGHT_DEFAULT_DOMAIN: pagewright.io

  serving:
    environment:
      PAGEWRIGHT_NGINX_RELOAD_COMMAND: "true"
